apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack-path-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack-path-express
  template:
    metadata:
      labels:
        app: attack-path-express
    spec:
      serviceAccountName: wiz-todo-sa
      containers:
      - name: app
        image: <ECR_URI>
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://<MONGO_IP>:27017"
